using OOS.OgrenciOtomasyonSistemi.EntityFrameworkCore;
using Xunit;

namespace OOS.OgrenciOtomasyonSistemi.EntityFrameworkCore;

public class OgrenciOtomasyonSistemiEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<OgrenciOtomasyonSistemiEntityFrameworkCoreFixture>
{

}
