using Xunit;

namespace OOS.OgrenciOtomasyonSistemi.EntityFrameworkCore;

[CollectionDefinition(OgrenciOtomasyonSistemiTestConsts.CollectionDefinitionName)]
public class OgrenciOtomasyonSistemiEntityFrameworkCoreCollection : ICollectionFixture<OgrenciOtomasyonSistemiEntityFrameworkCoreFixture>
{

}
